"""empty message

Revision ID: a2e4e833609e
Revises: bf21132e87b0
Create Date: 2023-11-06 04:53:18.962615

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2e4e833609e'
down_revision: Union[str, None] = 'bf21132e87b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('processed_images', sa.Column('result', sa.JSON(), nullable=False))
    op.add_column('processed_images', sa.Column('image_data', sa.LargeBinary(length=4056), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('processed_images', 'image_data')
    op.drop_column('processed_images', 'result')
    # ### end Alembic commands ###
