[default]
API_PREFIX = "/api/v1"
PROXY_ROOT_PATH = ""
API_URL_BASE = ""
SERVER_RELOAD = 1
SAVE_PREDICTION = 0

[production]
PROXY_ROOT_PATH = "/biomedic-ia-demonstration-backend"
API_URL_BASE = "https://lucaspraciano.com/biomedic-ia-demonstration-backend"
SERVER_RELOAD = 0

[development]
SERVER_RELOAD = 1

[testing]
SERVER_RELOAD = 0