name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    environment: prod

    env:
      BIOIADEMON_APP_RUNNING_MODE_TESTING: testing
      BIOIADEMON_DB_URL_TESTING: ${{ secrets.BIOIADEMON_DB_URL_TESTING }}

    services:
      db:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: abcd1234
          POSTGRES_DB: ia_hem_scan_testing
        ports:
          - "5432:5432"
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=5s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Wait for Postgres to be healthy
        run: sleep 10

      - name: Check out code
        uses: actions/checkout@v3

      - name: Build image
        run: |
          docker build \
            -f docker/Dockerfile.api \
            -t lucaspraciano/project-biomedic-ia-demonstrations-backend:v1
            .

      - name: Run test container
        run: |
          docker run --rm  --network host\
            -e BIOIADEMON_APP_RUNNING_MODE=${{ env.BIOIADEMON_APP_RUNNING_MODE_TESTING }} \
            -e BIOIADEMON_DB_URL=${{ secrets.BIOIADEMON_DB_URL_TESTING }} \
            lucaspraciano/project-biomedic-ia-demonstrations-backend:v1 \
            poetry run python run_tests.py

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_HUB_TOKEN }}" | docker login -u "lucaspraciano" --password-stdin

      - name: Tag image with commit SHA
        run: docker tag lucaspraciano/project-biomedic-ia-demonstrations-backend:v1 lucaspraciano/project-biomedic-ia-demonstrations-backend:${{ github.sha }}

      - name: Push image with commit SHA to Docker Hub
        run: docker push lucaspraciano/project-biomedic-ia-demonstrations-backend:${{ github.sha }}

      - name: Tag image as latest
        run: docker tag lucaspraciano/project-biomedic-ia-demonstrations-backend:${{ github.sha }} lucaspraciano/project-biomedic-ia-demonstrations-backend:latest

      - name: Push latest image to Docker Hub
        run: docker push lucaspraciano/project-biomedic-ia-demonstrations-backend:latest