name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    environment: prod

    env:
      BIOIADEMON_APP_RUNNING_MODE: production
      BIOIADEMON_DB_URL: ${{ secrets.BIOIADEMON_DB_URL }}
      POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
      POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}

    services:
      db:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: abcd1234
          POSTGRES_DB: ia_hem_scan_development
        ports:
          - "5432:5432"
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=5s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Wait for Postgres to be healthy
        run: sleep 10

      - name: Create second DB (ia_hem_scan_test)
        run: |
          DB_CONTAINER_ID=$(docker ps -q -f ancestor=postgres:15)
          docker exec "$DB_CONTAINER_ID" \
            psql -U postgres -c "CREATE DATABASE ia_hem_scan_testing;"

      - name: Build Docker image
        run: |
          docker build \
            -f docker/Dockerfile.api \
            -t lspraciano/project-biomedic-ia-demonstrations-backend:${{ github.sha }} \
            .

      - name: Run tests inside container
        run: |
          docker run --rm \
            -e BIOIADEMON_APP_RUNNING_MODE=${{ env.BIOIADEMON_APP_RUNNING_MODE }} \
            -e BIOIADEMON_DB_URL=${{ env.BIOIADEMON_DB_URL }} \
            lspraciano/project-biomedic-ia-demonstrations-backend:${{ github.sha }} \
            poetry run python run_tests.py