name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    environment: prod

    env:
      BIOIADEMON_APP_RUNNING_MODE: production
      BIOIADEMON_APP_RUNNING_MODE_TESTING: testing
      BIOIADEMON_DB_URL: ${{ secrets.BIOIADEMON_DB_URL }}
      BIOIADEMON_DB_URL_TESTING: ${{ secrets.BIOIADEMON_DB_URL_TESTING }}
      POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
      POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}

    services:
      db:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: abcd1234
          POSTGRES_DB: ia_hem_scan_testing
        ports:
          - "5432:5432"
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=5s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Wait for Postgres to be healthy
        run: sleep 10

      - name: Check out code
        uses: actions/checkout@v3

      - name: Build test image
        run: |
          docker build \
            -f docker/Dockerfile.api \
            --build-arg BIOIADEMON_APP_RUNNING_MODE=${{ secrets.BIOIADEMON_APP_RUNNING_MODE_TESTING }} \
            --build-arg BIOIADEMON_DB_URL=${{ secrets.BIOIADEMON_DB_URL_TESTING }} \
            -t myapp:test \
            .

      - name: Run test container
        run: |
          docker run --rm myapp:test poetry run python run_tests.py

      - name: Remove test image
        run: docker rmi myapp:test || true

      - name: Build prod image
        run: |
          docker build \
            -f docker/Dockerfile.api \
            --build-arg BIOIADEMON_APP_RUNNING_MODE=${{ secrets.BIOIADEMON_APP_RUNNING_MODE }} \
            --build-arg BIOIADEMON_DB_URL=${{ secrets.BIOIADEMON_DB_URL }} \
            -t myapp:prod \
            .